version: 2.0

jobs:
  persist:
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - run: mkdir -p test/subfolder
      - run: echo test > test/subfolder/test.txt
      - persist_to_workspace:
          root: .
          paths: test/subfolder

  attach:
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - attach_workspace:
          at: .
      - run: ls -R test
      - run: cat test/subfolder/test.txt

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - persist
      - attach:
          requires:
            - persist
